### ISSUE TITLE
Mixup returns different combinations for labels and images

### ISSUE THREAD

**Issue by itskalvik** [xudonmao/VMT#1]
The implementation of mixup seems to be wrong. We are supposed to use the same permutation for the labels and images. But the use of 2 separate random_shuffle calls will return a different combination of images and labels. 

https://github.com/xudonmao/VMT/blob/39476e4520a915e30327d190867c3122206b7243/codebase/models/extra_layers.py#L76

**Comment by xudonmao** [comment]
@kdkalvik  
Thanks for pointing this out. We have fixed the bug to have the same combination of images and labels. After fixing this bug, the performance of VMT can be further improved for almost all the tasks.

By the way, we need to change the values of some hyperparameters for the updated version. For example, for MNIST->SVHN with instance normalization, we change lambda_s and lambda_t to 1 and 0.08 respectively.
